language: erlang
notifications:
  email: false
before_install:
  - sudo apt-get install rabbitmq-server
before_script:
  - sudo service rabbitmq-server start
  - test/ct/bin/setup_test_env.sh
  - sudo rabbitmqctl report
  - sudo rabbitmqctl list_users
  - epmd -daemon
script: make travis
after_script:
  - cat logs/raw.log
  - cat test/ct/logs/raw.log
otp_release:
  - R16B03
